# ???????
server.port=14000
# ??Tomcat?????5???300000???????????????
server.tomcat.async-timeout=300000
# Tomcat??????1???60000???
server.tomcat.connection-timeout=60000
# ??????????
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true

# ???Nacos??????
spring.application.name=charging-ai
spring.cloud.nacos.discovery.server-addr=localhost:8848

# ????????????????
spring.ai.dashscope.api-key=sk-d7fe5fd2dfd64bad951a415b33307bd4
spring.ai.dashscope.agent.options.app-id=9e1598d11ba44ade84f47984bceaa900
spring.ai.dashscope.agent.incremental-output=true

# ?????????????????
spring.ai.dashscope.timeout.connect=60000       # ????30?
spring.ai.dashscope.timeout.read=300000         # ????5??
# ?????spring.webflux?????SDK??????