# AI???application.properties ???????
server.port=14000
# ??????charging-ai????lb://?????????
spring.application.name=charging-ai
# Nacos???????????Nacos?????
spring.cloud.nacos.discovery.server-addr=localhost:8848
# ???????
spring.ai.dashscope.api-key=sk-d7fe5fd2dfd64bad951a415b33307bd4
spring.ai.dashscope.agent.options.app-id=9e1598d11ba44ade84f47984bceaa900
spring.ai.dashscope.agent.incremental-output=true
# ??????...